Improve 404 error handling
sindresorhus/npm-email pull request #9
Opened 2024-02-28 19:42 UTC by tommy-mitchell

Similar to https://github.com/sindresorhus/npm-user/pull/23

2024-02-28 20:03 UTC, sindresorhus requested changes

2024-02-28 20:03 UTC, sindresorhus commented on test.js
> +	globalThis.fetch = async () => {
You need to reset this back at the end of the test.

2024-02-28 20:03 UTC, sindresorhus commented on test.js
> +test.serial('invalid input', async t => {
No reason these have to be serial.

2024-02-28 20:03 UTC, sindresorhus commented on index.js
> +			return undefined;
```suggestion
			return;
```

2024-02-28 20:24 UTC, tommy-mitchell commented on test.js
> +test.serial('invalid input', async t => {
Yeah, I was being lazy to avoid resetting the `fetch` mock lol. Will update.

2024-02-28 20:27 UTC, tommy-mitchell commented
Updated.

2024-02-29 05:56 UTC, sindresorhus commented on test.js
> +test('handles 404', async t => {
I meant the other tests. This one does indeed need to be serial because of the mocking.

2024-02-29 06:27 UTC, merged